In [1]:
import numpy as np
import pandas as pd

Considere os arrays numpy X, y abaixo:

In [2]:
from sklearn.datasets import load_iris

X = load_iris().data
y = load_iris().target

In [3]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

__Exercício 1:__ Crie um dataframe df do pandas a partir de X, y.

Primeiro, concatene os arrays numpy. Na sequência transforme o array final para um dataframe. Altere o nome das colunas para 'X1', 'X2', 'X3', 'X4' e 'target'.

In [5]:
#concatenando os arrays:

arr_c_ = np.c_[X,y]

print(arr_c_)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [6]:
#criando dataframe a partir do array final:
df = pd.DataFrame(arr_c_, columns=["X1","X2","X3","X4","target"])

df

X1   X2   X3   X4  target
0    5.1  3.5  1.4  0.2     0.0
1    4.9  3.0  1.4  0.2     0.0
2    4.7  3.2  1.3  0.2     0.0
3    4.6  3.1  1.5  0.2     0.0
4    5.0  3.6  1.4  0.2     0.0
..   ...  ...  ...  ...     ...
145  6.7  3.0  5.2  2.3     2.0
146  6.3  2.5  5.0  1.9     2.0
147  6.5  3.0  5.2  2.0     2.0
148  6.2  3.4  5.4  2.3     2.0
149  5.9  3.0  5.1  1.8     2.0

[150 rows x 5 columns]

__Exercício 2:__ Usando o df criado no exercício 1, calcule qual a média da variável 'X2', para cada valor de target. Dica: Use a função groupby no dataframe df para resolver.

In [7]:
#agrupando os dados de X2 e calculando média:

df.groupby(by = "target").apply(lambda x: x.X2.mean())

target
0.0    3.428
1.0    2.770
2.0    2.974
dtype: float64

__Exercício 3:__ Construa um dicionário mapeando os valores:
        
        0 - 'A'
        
        1 - 'B'
        
        2 - 'C'
        
Usando a função map, crie uma coluna nova no dataframe df chamada 'target_2' com o mapeamento feito. Dica: Use a função map como visto em aula.

In [8]:
df['target2'] = df['target'].map({0:'A',1:'B',2:'C'},na_action=None)

df

X1   X2   X3   X4  target target2
0    5.1  3.5  1.4  0.2     0.0       A
1    4.9  3.0  1.4  0.2     0.0       A
2    4.7  3.2  1.3  0.2     0.0       A
3    4.6  3.1  1.5  0.2     0.0       A
4    5.0  3.6  1.4  0.2     0.0       A
..   ...  ...  ...  ...     ...     ...
145  6.7  3.0  5.2  2.3     2.0       C
146  6.3  2.5  5.0  1.9     2.0       C
147  6.5  3.0  5.2  2.0     2.0       C
148  6.2  3.4  5.4  2.3     2.0       C
149  5.9  3.0  5.1  1.8     2.0       C

[150 rows x 6 columns]

__Exercício 4:__ 


4.1: Filtre o dataframe df onde X1 é maior do que 6 __ou__ target é diferente de 2 e chame-o de df1. Dica: usar os filtros e os operadores vistos em aula;

4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2;

4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final. Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação.

In [9]:
#4.1: Filtre o dataframe df onde X1 é maior do que 6 ou target é diferente de 2 e chame-o de df1
df1 = df[(df.X1>6) & (df.target!=2)]

df1

X1   X2   X3   X4  target target2
50  7.0  3.2  4.7  1.4     1.0       B
51  6.4  3.2  4.5  1.5     1.0       B
52  6.9  3.1  4.9  1.5     1.0       B
54  6.5  2.8  4.6  1.5     1.0       B
56  6.3  3.3  4.7  1.6     1.0       B
58  6.6  2.9  4.6  1.3     1.0       B
63  6.1  2.9  4.7  1.4     1.0       B
65  6.7  3.1  4.4  1.4     1.0       B
68  6.2  2.2  4.5  1.5     1.0       B
71  6.1  2.8  4.0  1.3     1.0       B
72  6.3  2.5  4.9  1.5     1.0       B
73  6.1  2.8  4.7  1.2     1.0       B
74  6.4  2.9  4.3  1.3     1.0       B
75  6.6  3.0  4.4  1.4     1.0       B
76  6.8  2.8  4.8  1.4     1.0       B
77  6.7  3.0  5.0  1.7     1.0       B
86  6.7  3.1  4.7  1.5     1.0       B
87  6.3  2.3  4.4  1.3     1.0       B
91  6.1  3.0  4.6  1.4     1.0       B
97  6.2  2.9  4.3  1.3     1.0       B

In [10]:
#4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2
df2 = df.iloc[:16]

df2

X1   X2   X3   X4  target target2
0   5.1  3.5  1.4  0.2     0.0       A
1   4.9  3.0  1.4  0.2     0.0       A
2   4.7  3.2  1.3  0.2     0.0       A
3   4.6  3.1  1.5  0.2     0.0       A
4   5.0  3.6  1.4  0.2     0.0       A
5   5.4  3.9  1.7  0.4     0.0       A
6   4.6  3.4  1.4  0.3     0.0       A
7   5.0  3.4  1.5  0.2     0.0       A
8   4.4  2.9  1.4  0.2     0.0       A
9   4.9  3.1  1.5  0.1     0.0       A
10  5.4  3.7  1.5  0.2     0.0       A
11  4.8  3.4  1.6  0.2     0.0       A
12  4.8  3.0  1.4  0.1     0.0       A
13  4.3  3.0  1.1  0.1     0.0       A
14  5.8  4.0  1.2  0.2     0.0       A
15  5.7  4.4  1.5  0.4     0.0       A

In [11]:
#4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 
#(use a função que calcula transposta de matriz) e printe o resultado final. 
#Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação

df1_alt = df1.drop(["target2"], axis=1)

df1_alt

X1   X2   X3   X4  target
50  7.0  3.2  4.7  1.4     1.0
51  6.4  3.2  4.5  1.5     1.0
52  6.9  3.1  4.9  1.5     1.0
54  6.5  2.8  4.6  1.5     1.0
56  6.3  3.3  4.7  1.6     1.0
58  6.6  2.9  4.6  1.3     1.0
63  6.1  2.9  4.7  1.4     1.0
65  6.7  3.1  4.4  1.4     1.0
68  6.2  2.2  4.5  1.5     1.0
71  6.1  2.8  4.0  1.3     1.0
72  6.3  2.5  4.9  1.5     1.0
73  6.1  2.8  4.7  1.2     1.0
74  6.4  2.9  4.3  1.3     1.0
75  6.6  3.0  4.4  1.4     1.0
76  6.8  2.8  4.8  1.4     1.0
77  6.7  3.0  5.0  1.7     1.0
86  6.7  3.1  4.7  1.5     1.0
87  6.3  2.3  4.4  1.3     1.0
91  6.1  3.0  4.6  1.4     1.0
97  6.2  2.9  4.3  1.3     1.0

In [12]:
df2_t = df2.drop(["target2"], axis=1).T

df2_t

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
X1      5.1  4.9  4.7  4.6  5.0  5.4  4.6  5.0  4.4  4.9  5.4  4.8  4.8  4.3   
X2      3.5  3.0  3.2  3.1  3.6  3.9  3.4  3.4  2.9  3.1  3.7  3.4  3.0  3.0   
X3      1.4  1.4  1.3  1.5  1.4  1.7  1.4  1.5  1.4  1.5  1.5  1.6  1.4  1.1   
X4      0.2  0.2  0.2  0.2  0.2  0.4  0.3  0.2  0.2  0.1  0.2  0.2  0.1  0.1   
target  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

         14   15  
X1      5.8  5.7  
X2      4.0  4.4  
X3      1.2  1.5  
X4      0.2  0.4  
target  0.0  0.0

In [13]:
#multiplicação das matrizes:
np.dot(df1_alt,df2_t)

array([[53.76, 50.76, 49.53, 49.45, 53.38, 58.83, 50.08, 53.21, 46.94,
        51.41, 56.97, 52.28, 49.92, 45.01, 59.32, 61.59],
       [50.44, 47.56, 46.47, 46.41, 50.12, 55.29, 47.07, 49.93, 44.04,
        48.18, 53.45, 49.1 , 46.77, 42.22, 55.62, 57.91],
       [53.2 , 50.27, 49.02, 49.  , 52.82, 58.28, 49.59, 52.69, 46.51,
        50.92, 56.38, 51.8 , 49.43, 44.51, 58.6 , 60.92],
       [49.69, 46.99, 45.79, 45.78, 49.32, 54.44, 46.31, 49.22, 43.46,
        47.58, 52.66, 48.38, 46.19, 41.56, 54.72, 56.87],
       [50.58, 47.67, 46.6 , 46.58, 50.28, 55.52, 47.26, 50.09, 44.19,
        48.31, 53.6 , 49.3 , 46.88, 42.32, 55.7 , 58.12],
       [50.51, 47.74, 46.54, 46.51, 50.14, 55.29, 47.05, 50.02, 44.15,
        48.36, 53.53, 49.16, 46.95, 42.27, 55.66, 57.8 ],
       [48.12, 45.45, 44.34, 44.38, 47.8 , 52.8 , 44.92, 47.69, 42.11,
        46.07, 51.  , 46.94, 44.7 , 40.24, 52.9 , 55.14],
       [51.46, 48.57, 47.41, 47.31, 51.1 , 56.31, 47.94, 50.92, 44.91,
        49.18, 54.53, 50.0

__Exercício 5:__ 
    
5.1: Crie uma função que receba um  número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays;
    
5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatórias SEM reposição;

5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números.

In [14]:
#5.1: Crie uma função que receba um número inteiro positivo N e retorne um array 0, 1, ..., N.

n = 15

if n >= 0:
    arr_ativ = np.arange(n + 1)
    print(arr_ativ)
else:
    print("O número inserido não é um inteiro positivo.")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [15]:
#5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias.

arr_ativ2 = np.array([0,1,2,3,4,5,6])
print("Array inicial:", arr_ativ2)

print("----------------------------")

np.random.shuffle(arr_ativ2)
print("Array posições aleatórias:", arr_ativ2)

Array inicial: [0 1 2 3 4 5 6]
----------------------------
Array posições aleatórias: [2 3 5 1 6 4 0]


In [16]:
#5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, 
#cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números.

n = 6

if n >= 0:
    arr_ativ = np.random.choice(n - 1, size = n)
    print(arr_ativ)
else:
    print("O número inserido não é um inteiro positivo.")

[4 1 0 2 4 0]


__Exercício 6:__ Construa uma função divide_dados:
        
        - recebe um array X de dimensões quaisquer (n,k) e um parâmetro p entre 0 e 1.
        - divide o array X em duas partes disjuntas de forma aleatória. Ou seja, crie dois novos arrays, X1 e X2,
        onde a dimensão de linhas de X1 somada com a dimensão de linhas de X2 deve ser igual a dimensão de linhas de X.
        - interpretando p como percentual, o tamanho de X1 deve ser p*100% do número de linhas de X; enquanto X2 deve ser o resto.
        - retorne esses dois arrays.

In [17]:
x = np.random.rand(10, 2) #array x -> 10 linhas e 2 colunas
p = 70 #percentual entre 0 e 100

size_x = len(x) #tamanho de x
size_x1 = p*(size_x/100) #cálculo tamanho de x1
size_x2 = size_x - size_x1 #cálculo tamanho de x2

#dividindo o array em 2
x1_idx = np.random.randint(x.shape[0], size=int(size_x1)) 
x2_idx = np.random.randint(x.shape[0], size=int(size_x2))
x1, x2 = x[x1_idx,:], x[x2_idx,:]

print("x1:", x1)
print("**************")
print("x2:", x2)

x1: [[0.11229242 0.53645227]
 [0.2693898  0.37499717]
 [0.18462971 0.76492316]
 [0.0926426  0.75246998]
 [0.18462971 0.76492316]
 [0.38010254 0.45956644]
 [0.18462971 0.76492316]]
**************
x2: [[0.034421   0.40827792]
 [0.11229242 0.53645227]
 [0.0926426  0.75246998]]
